# -*- coding: utf-8 -*-
"""own_python_practice.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dgcJCZ_7PSy843eXeZfe8eAuyFwS720a

## String 
Collection of character inside of "double quotes" or 'single quotes'
"""

print("Hello 'world' world")

print('Hello "world" world')

print("""Hello world 
We are here""")

print('''Hello chair 
Please sit here
 for me''')

"""# Escape Sequence 
To insert characters that are illegal in a string, use an escape character.

\'   -  single quotes

\"   -  double quotes

\\   -  backslash 

\n   -  newline

\t   -  tab

\b   - backspace
"""

# The whole line we want in comment by using shorcut key ( ctrl + press/)

"""## How to use escape sequence as normal text """

# Output : line A \n line B

print("Line A \\n Line B")

# Output : \"  \'

print("\\\"  \\\'")

"""## Assignment for escape sequence"""

# 1. This is \\ double backslash

print("This id \\\\ double backslash")

# 2. These are /\/\/\/\/\ mountains

print("These are /\\/\\/\\/\\/\\ mountains")

# He is                   awesome (use escape sequnece only )

print("He is \t\t awesome")

"""## Raw string ( when without using escape sequence)"""

print(r"line A \n line B")

"""## Concatenate ( strings) """

first_name = "Tanu"
last_name = "Shree"
full_name = first_name + last_name

print(full_name)

full_name = first_name+ " " + last_name

print(full_name)

print(first_name +3)

print(first_name +"3")

print(first_name +str(3))

print(first_name*3)

#User Input
#input function
# note : input function always take string only

name= input("Type you name please : ")

print("hello ! "+ name)

age=input("what is you age ")

num1 = input("enter first number")
num2 = input ("enter second number")

total = num1 + num2
print("total is "+ total)         # input always take strigs only ; output : "6" + "3" = 63 not give 9

num3 = int(input("enter first number"))
num4 = int(input ("enter second number"))

total_ = num3 + num4
print("total is "+ total_)

total_ = num3 + num4
print("total is "+ str(total_))

# string methods

name= " Tanushree Sahu "

#len() function     ( its counts space also)
print(len(name))

#lower() methods
name="SHREE TANU "
namy="tanushree"

print(name.lower())

print(namy.upper())

print(name.title())

print(name.count("E"))

"""23-08-2022"""

#A company decided to give bonus of 5% to employee if his/her year of service is more than 5 years.
#Ask user for their salary and year of service and print the net bonus amount.

user_sal=int(input("enter your salary:"))
user_service_year=int(input("enter your no of service year:"))

if user_service_year>5:
  bonus=0.05*user_sal
  print("your Bonus is:",bonus)
else:
  print("No bonus")

#Take values of length and breadth of a rectangle from user and check if it is square or not.
l1=int(input("enter length:"))
b1=int(input("enter breath :"))

if l1==b1:
  print("Its a square")
else:
  print("Its not a square")

#Take two int values from user and print greatest among them.
num1=int(input("enter first no:"))
num2=int(input("enter second no:"))

if num1>num2:
  print("number1 is greater")
elif num1<num2:
  print("number2 is greater than number 1")
else:
  print("both are equal")

#A shop will give discount of 10% if the cost of purchased quantity is more than 1000.
#Suppose, one unit will cost 100.
items=int(input("enter the purchased quantity :"))
if items>1000:
  discount_offer=0.1*items*100
  cost=(items*100)-discount_offer
  print("after discounted cost:",cost)
else:("cost is ",items*100)







